<?php
/**
 * Contains MeetingRepository class
 */
namespace AppBundle\Repository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class MeetingRepository
 * @package AppBundle\Repository
 */
class MeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
