<?php
/**
 * Created by PhpStorm.
 * User: Pierre
 * Date: 01/05/2016
 * Time: 17:56
 */

namespace AppBundle\Repository;

/**
 * MeetingAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class MeetingMinutesRepository
 * @package AppBundle\Repository
 */
class MeetingMinutesRepository extends \Doctrine\ORM\EntityRepository
{

}