<?php

namespace AppBundle\Repository;

/**
 * MeetingMinutesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingMinutesRepository extends \Doctrine\ORM\EntityRepository
{
}
