<?php
/**
 * Created by PhpStorm.
 * User: Pierre
 * Date: 02/05/2016
 * Time: 00:12
 */

namespace AppBundle\Repository;

/**
 * MeetingAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class MinuteItemRepository
 * @package AppBundle\Repository
 */
class MinuteItemRepository extends \Doctrine\ORM\EntityRepository
{

}