<?php

namespace AppBundle\Repository;

/**
 * MinuteActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinuteActionRepository extends \Doctrine\ORM\EntityRepository
{
}
