<?php
/**
 * Created by PhpStorm.
 * User: Pierre
 * Date: 01/05/2016
 * Time: 19:03
 */

namespace AppBundle\Repository;

/**
 * MeetingAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class PresenceRepository
 * @package AppBundle\Repository
 */
class PresenceRepository extends \Doctrine\ORM\EntityRepository
{

}