<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class ProjectRepository
 * @package AppBundle\Repository
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
